name: model-training
on:
   pull_request:
    branches: [ master ]

jobs:
  ML-CI:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -i --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \ 
          --header 'content-type: application/json' \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/check-runs \
          -d '{"name":"Model-training","head_sha":"$GITHUB_SHA","status":"in_progress","external_id":"$GITHUB_SHA"}'
          
